float:
  any:
  - base_args: ['@metric']
    constructor: HnswLib
    disabled: false
    docker_tag: ann-benchmarks-hnswlib
    module: ann_benchmarks.algorithms.hnswlib
    name: hnswlib
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 500}]
        args: {}
        query_args: [[10]]
      M-16:
        arg_groups: [{M: 16, efConstruction: 500}]
        args: {}
        query_args: [[10]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 500}]
        args: {}
        query_args: [[10]]
      M-24-20:
        arg_groups: [{M: 24, efConstruction: 500}]
        args: {}
        query_args: [[20]]
